version: '3'
services:
  wenv:
    ## image: docker.io/natbodocker/virtualrobotdisi:2.0
    image: virtualrobotdisi:2.0
    ports:
      - 8090:8090
      - 8091:8091
  stepper:
    image: steprobot:1.0
    ports:
      - 8010:8010
    depends_on:
      - wenv



## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## Compose does not wait until a container is “ready” (whatever that means for your particular application)
## - only until it’s running. There’s a good reason for this.
## The best solution is to perform this check in your application code,
## -------------------------------------------------------------
## docker-compose run --service-ports wenv
## docker-compose run --service-ports vrobotclient  ATTIVA ANCHE wenv