version: '3'
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi:2.0
    ##image: virtualrobotdisi:2.0
    ports:
      - 8090:8090
      - 8091:8091
  stepper:
    ##image: steprobot:1.0
    image: docker.io/natbodocker/steprobot:1.0
    ports:
      - 8010:8010
    depends_on:
      - wenv

##it.unibo.kotlinSupports>docker-compose -f virtualrobotandstepper.yaml up