version: '3'
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi:2.0
    ##image: virtualrobotdisi:2.0
    ports:
      - 8090:8090
      - 8091:8091
  serverspring8081:
    image: webspringrobot:1.0.1
    ## image: docker.io/natbodocker/webspringrobot:1.0.1
    ports:
      - 8081:8081
    depends_on:
      - wenv

##it.unibo.kotlinSupports>docker-compose -f virtualrobotguistepper.yaml up